# Generated by Django 4.1.3 on 2023-06-08 07:04

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=phone_field.models.PhoneField(help_text='Contact phone number', max_length=31),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(upload_to='profileimg'),
        ),
    ]
