# Generated by Django 4.1.3 on 2023-06-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='resume',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='gender',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='resume',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='pimage',
            field=models.ImageField(upload_to='pimages'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='rdocs',
            field=models.FileField(upload_to='rdocs'),
        ),
    ]
